###@server = https://insensebot-turbo-space-cod-jxrq5g9747425jp9-8080.preview.app.github.dev

@server = https://semana8-practica.onrender.com
@apiserver = {{server}}/api/curso

GET {{server}}/

###
GET {{server}}/codigo

###
GET {{server}}/nombre-completo

###
GET {{apiserver}}/listar

###
POST {{apiserver}}/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=Inteligencia Artificial
&creditos=5

###
DELETE {{apiserver}}/eliminar
Content-Type: application/x-www-form-urlencoded

id=2