###@server = https://insensebot-turbo-space-cod-jxrq5g9747425jp9-8080.preview.app.github.dev
###@server = https://semana8-practica.onrender.com
@server = https://insensebot-turbo-space-cod-jxrq5g9747425jp9-8828.preview.app.github.dev

###
GET {{server}}/

###
GET {{server}}/cursos

###
GET {{server}}/cursos/52

###
GET {{server}}/cursos?size=2

###
GET {{server}}/cursos?size=2&page=1

###
GET {{server}}/cursos?sort=creditos.desc

###
POST {{server}}/cursos
Content-Type: application/json

{"nombre": "Compiladores", "creditos": 5}

###
DELETE {{server}}/cursos/52

###
PATCH {{server}}/cursos/52
Content-Type: application/json

{"creditos": 5}

###
GET {{server}}/profile/cursos

###
GET {{server}}/cursos/search/findByNombre?nombre=Inteligencia+Artificial

############ Carrera
GET {{server}}/carreras
###
POST {{server}}/carreras
Content-Type: application/json

{"nombre": "Desarrollo de Software"}

###
GET {{server}}/cursos/2/carrera

###
GET {{server}}/carreras/1

###
GET {{server}}/carreras/1/cursos